defmodule CatalogApi.Address.Iso3166 do
  @moduledoc false

  @doc false
  @spec validate(any()) :: :ok | :error
  def validate("AB"), do: :ok
  def validate("AD"), do: :ok
  def validate("AE"), do: :ok
  def validate("AF"), do: :ok
  def validate("AG"), do: :ok
  def validate("AI"), do: :ok
  def validate("AL"), do: :ok
  def validate("AM"), do: :ok
  def validate("AO"), do: :ok
  def validate("AQ"), do: :ok
  def validate("AR"), do: :ok
  def validate("AS"), do: :ok
  def validate("AT"), do: :ok
  def validate("AU"), do: :ok
  def validate("AW"), do: :ok
  def validate("AX"), do: :ok
  def validate("AZ"), do: :ok
  def validate("BA"), do: :ok
  def validate("BB"), do: :ok
  def validate("BD"), do: :ok
  def validate("BE"), do: :ok
  def validate("BF"), do: :ok
  def validate("BG"), do: :ok
  def validate("BH"), do: :ok
  def validate("BI"), do: :ok
  def validate("BJ"), do: :ok
  def validate("BL"), do: :ok
  def validate("BM"), do: :ok
  def validate("BN"), do: :ok
  def validate("BO"), do: :ok
  def validate("BQ"), do: :ok
  def validate("BQ"), do: :ok
  def validate("BR"), do: :ok
  def validate("BS"), do: :ok
  def validate("BT"), do: :ok
  def validate("BV"), do: :ok
  def validate("BW"), do: :ok
  def validate("BY"), do: :ok
  def validate("BZ"), do: :ok
  def validate("CA"), do: :ok
  def validate("CC"), do: :ok
  def validate("CD"), do: :ok
  def validate("CF"), do: :ok
  def validate("CG"), do: :ok
  def validate("CH"), do: :ok
  def validate("CI"), do: :ok
  def validate("CK"), do: :ok
  def validate("CL"), do: :ok
  def validate("CM"), do: :ok
  def validate("CN"), do: :ok
  def validate("CO"), do: :ok
  def validate("CR"), do: :ok
  def validate("CU"), do: :ok
  def validate("CV"), do: :ok
  def validate("CW"), do: :ok
  def validate("CX"), do: :ok
  def validate("CY"), do: :ok
  def validate("CZ"), do: :ok
  def validate("DE"), do: :ok
  def validate("DJ"), do: :ok
  def validate("DK"), do: :ok
  def validate("DM"), do: :ok
  def validate("DO"), do: :ok
  def validate("DZ"), do: :ok
  def validate("EC"), do: :ok
  def validate("EE"), do: :ok
  def validate("EG"), do: :ok
  def validate("EH"), do: :ok
  def validate("ER"), do: :ok
  def validate("ES"), do: :ok
  def validate("ET"), do: :ok
  def validate("FI"), do: :ok
  def validate("FJ"), do: :ok
  def validate("FK"), do: :ok
  def validate("FM"), do: :ok
  def validate("FO"), do: :ok
  def validate("FR"), do: :ok
  def validate("GA"), do: :ok
  def validate("GB"), do: :ok
  def validate("GD"), do: :ok
  def validate("GE"), do: :ok
  def validate("GF"), do: :ok
  def validate("GG"), do: :ok
  def validate("GH"), do: :ok
  def validate("GI"), do: :ok
  def validate("GL"), do: :ok
  def validate("GM"), do: :ok
  def validate("GN"), do: :ok
  def validate("GP"), do: :ok
  def validate("GQ"), do: :ok
  def validate("GR"), do: :ok
  def validate("GS"), do: :ok
  def validate("GT"), do: :ok
  def validate("GU"), do: :ok
  def validate("GW"), do: :ok
  def validate("GY"), do: :ok
  def validate("HK"), do: :ok
  def validate("HM"), do: :ok
  def validate("HN"), do: :ok
  def validate("HR"), do: :ok
  def validate("HT"), do: :ok
  def validate("HU"), do: :ok
  def validate("ID"), do: :ok
  def validate("IE"), do: :ok
  def validate("IL"), do: :ok
  def validate("IM"), do: :ok
  def validate("IN"), do: :ok
  def validate("IO"), do: :ok
  def validate("IQ"), do: :ok
  def validate("IR"), do: :ok
  def validate("IS"), do: :ok
  def validate("IT"), do: :ok
  def validate("JE"), do: :ok
  def validate("JM"), do: :ok
  def validate("JO"), do: :ok
  def validate("JP"), do: :ok
  def validate("KE"), do: :ok
  def validate("KG"), do: :ok
  def validate("KH"), do: :ok
  def validate("KI"), do: :ok
  def validate("KM"), do: :ok
  def validate("KN"), do: :ok
  def validate("KP"), do: :ok
  def validate("KR"), do: :ok
  def validate("KW"), do: :ok
  def validate("KY"), do: :ok
  def validate("KZ"), do: :ok
  def validate("LA"), do: :ok
  def validate("LB"), do: :ok
  def validate("LC"), do: :ok
  def validate("LI"), do: :ok
  def validate("LK"), do: :ok
  def validate("LR"), do: :ok
  def validate("LS"), do: :ok
  def validate("LT"), do: :ok
  def validate("LU"), do: :ok
  def validate("LV"), do: :ok
  def validate("LY"), do: :ok
  def validate("MA"), do: :ok
  def validate("MC"), do: :ok
  def validate("MD"), do: :ok
  def validate("ME"), do: :ok
  def validate("MF"), do: :ok
  def validate("MG"), do: :ok
  def validate("MH"), do: :ok
  def validate("MK"), do: :ok
  def validate("ML"), do: :ok
  def validate("MM"), do: :ok
  def validate("MN"), do: :ok
  def validate("MO"), do: :ok
  def validate("MP"), do: :ok
  def validate("MQ"), do: :ok
  def validate("MR"), do: :ok
  def validate("MS"), do: :ok
  def validate("MT"), do: :ok
  def validate("MU"), do: :ok
  def validate("MV"), do: :ok
  def validate("MW"), do: :ok
  def validate("MX"), do: :ok
  def validate("MY"), do: :ok
  def validate("MZ"), do: :ok
  def validate("NA"), do: :ok
  def validate("NC"), do: :ok
  def validate("NE"), do: :ok
  def validate("NF"), do: :ok
  def validate("NG"), do: :ok
  def validate("NI"), do: :ok
  def validate("NL"), do: :ok
  def validate("NO"), do: :ok
  def validate("NP"), do: :ok
  def validate("NR"), do: :ok
  def validate("NU"), do: :ok
  def validate("NZ"), do: :ok
  def validate("OM"), do: :ok
  def validate("PA"), do: :ok
  def validate("PE"), do: :ok
  def validate("PF"), do: :ok
  def validate("PG"), do: :ok
  def validate("PH"), do: :ok
  def validate("PK"), do: :ok
  def validate("PL"), do: :ok
  def validate("PM"), do: :ok
  def validate("PN"), do: :ok
  def validate("PR"), do: :ok
  def validate("PS"), do: :ok
  def validate("PT"), do: :ok
  def validate("PW"), do: :ok
  def validate("PY"), do: :ok
  def validate("QA"), do: :ok
  def validate("RE"), do: :ok
  def validate("RO"), do: :ok
  def validate("RS"), do: :ok
  def validate("RU"), do: :ok
  def validate("RW"), do: :ok
  def validate("SA"), do: :ok
  def validate("SB"), do: :ok
  def validate("SC"), do: :ok
  def validate("SD"), do: :ok
  def validate("SE"), do: :ok
  def validate("SG"), do: :ok
  def validate("SH"), do: :ok
  def validate("SI"), do: :ok
  def validate("SJ"), do: :ok
  def validate("SK"), do: :ok
  def validate("SL"), do: :ok
  def validate("SM"), do: :ok
  def validate("SN"), do: :ok
  def validate("SO"), do: :ok
  def validate("SR"), do: :ok
  def validate("SS"), do: :ok
  def validate("ST"), do: :ok
  def validate("SV"), do: :ok
  def validate("SX"), do: :ok
  def validate("SY"), do: :ok
  def validate("SZ"), do: :ok
  def validate("TC"), do: :ok
  def validate("TD"), do: :ok
  def validate("TF"), do: :ok
  def validate("TG"), do: :ok
  def validate("TH"), do: :ok
  def validate("TJ"), do: :ok
  def validate("TK"), do: :ok
  def validate("TL"), do: :ok
  def validate("TM"), do: :ok
  def validate("TN"), do: :ok
  def validate("TO"), do: :ok
  def validate("TR"), do: :ok
  def validate("TT"), do: :ok
  def validate("TV"), do: :ok
  def validate("TW"), do: :ok
  def validate("TZ"), do: :ok
  def validate("UA"), do: :ok
  def validate("UG"), do: :ok
  def validate("UM"), do: :ok
  def validate("US"), do: :ok
  def validate("UY"), do: :ok
  def validate("UZ"), do: :ok
  def validate("VA"), do: :ok
  def validate("VC"), do: :ok
  def validate("VE"), do: :ok
  def validate("VG"), do: :ok
  def validate("VI"), do: :ok
  def validate("VN"), do: :ok
  def validate("VU"), do: :ok
  def validate("WF"), do: :ok
  def validate("WS"), do: :ok
  def validate("YE"), do: :ok
  def validate("YT"), do: :ok
  def validate("ZA"), do: :ok
  def validate("ZM"), do: :ok
  def validate("ZW"), do: :ok
  def validate(_), do: :error
end
